name: mpra_analysis
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # Python and core packages
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scipy
  - statsmodels
  - jupyterlab
  - ipython
  
  # Additional utilities
  - pip
  
  # Install MPRAlib via pip
  - pip:
    - mpralib==0.9.1
